### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by AndreBlackScribe** [tulth/g600prog#1]
On running 
`$ sudo ./g600prog.py MOUSE`

Error:
```
  File "./g600prog.py", line 458
    raise FromJsonError(errStr + str(err)) from err
                                              ^
SyntaxError: invalid syntax
[Black@linux g600prog]$ sudo ./g600prog.py MOUSE
  File "./g600prog.py", line 458
    raise FromJsonError(errStr + str(err)) from err
                                              ^
SyntaxError: invalid syntax
```

AnY solutions?

**Comment by tulth** [comment]
it has been a long time since I have looked at this code but the from err is a python 3 construct.  if you run it with py3 i think you will have more luck

**Comment by tulth** [comment]
I ran this over the weekend and it works fine as long as python is python3
